---
version: "1.0.1"
name: OpenTherm Monitor
slug: otmonitor
description: OpenTherm Monitor to monitor and control OTGW device
url: "https://github.com/antst/hass_addons/tree/master/otmonitor"
arch:
  - aarch64
  - amd64
  - i386
image: antst/{arch}-addon-otmonitor
ports:
  8099/tcp: null
  7686/tcp: 7686
ports_description:
  8099/tcp: Web-server port
  7686/tcp: Relay port
startup: application
boot: auto
ingress: true
timeout: 30
panel_icon:
services:
  mqtt:need
schema:
  additional_options: str?
watchdog: http://[HOST]:8080
init: false
