---
version: 1.0.2
name: Anonymous Mosquitto broker
slug: anonymous_mosquitto
description: An Open Source MQTT broker. Clone of official addon, but with enabled back option for anonymous mode.
url: https://github.com/antst/hass_addons/tree/master/anonymous-mosquitto
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
auth_api: true
discovery:
  - mqtt
image: antst/{arch}-addon-anonymous-mosquitto
map:
  - ssl
  - share
options:
  logins: []
  anonymous: true
  require_certificate: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  customize:
    active: false
    folder: mosquitto
ports:
  1883/tcp: 1883
  1884/tcp: 1884
  8883/tcp: 8883
  8884/tcp: 8884
schema:
  logins:
    - username: str
      password: password
      password_pre_hashed: "bool?"
  anonymous: bool
  require_certificate: bool
  certfile: str
  cafile: str?
  keyfile: str
  customize:
    active: bool
    folder: str
  debug: bool?
services:
  - mqtt:provide
startup: system
watchdog: tcp://[HOST]:1883
init: false
